Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 13d1fd5] Automated commit from script - Updated Data
 4 files changed, 404 insertions(+), 6064 deletions(-)
 rewrite logfile.log (100%)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   807dc13..13d1fd5  main -> main

Script ended.
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Script started.
Traceback (most recent call last):
  File "D:\Projects\JobFinder\backend\mainScraper.py", line 738, in <module>
    log_message("Script started.")
  File "D:\Projects\JobFinder\backend\mainScraper.py", line 733, in log_message
    with open(log_file, 'a') as f:
         ^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'D:\\Projects\\JobFinder\\backend\\logfile.log'
Python script encountered an error. 
Script started.
Traceback (most recent call last):
  File "D:\Projects\JobFinder\backend\mainScraper.py", line 738, in <module>
    log_message("Script started.")
  File "D:\Projects\JobFinder\backend\mainScraper.py", line 733, in log_message
    with open(log_file, 'a') as f:
         ^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'D:\\Projects\\JobFinder\\backend\\logfile.log'
Python script encountered an error. 
Script started.
Traceback (most recent call last):
  File "D:\Projects\JobFinder\backend\mainScraper.py", line 738, in <module>
    log_message("Script started.")
  File "D:\Projects\JobFinder\backend\mainScraper.py", line 733, in log_message
    with open(log_file, 'a') as f:
         ^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'D:\\Projects\\JobFinder\\backend\\logfile.log'
Python script encountered an error. 
2024-08-05 11:22:18 - Script started.

2024-08-05 11:22:18 - Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json

2024-08-05 11:22:18 - Fetched chat IDs

2024-08-05 11:22:18 - Initiating emergency self destroy protocol...

2024-08-05 11:22:18 - Starting Telegram client

2024-08-05 11:27:30 - Disconnecting Telegram client

2024-08-05 11:27:30 - Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json

2024-08-05 11:27:30 - New instance of Robo created and data saved

2024-08-05 11:27:30 - Running git add

